---
name: "cloudbees"
paging:
  location_from: ""
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}"
  - "{{}}"
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  domain: "DOMAIN"
endpoints:
  - name: "connectionCheck"
    vars:
      service: "jobs"
    endpoint: "{{domain}}/api/json"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "jobs" ]
    desired_base_key: [ "Jobs" ]
    current_error_key: [ "error" ]
    desired_error_key: [ "Errors" ]
    documentation: ""
    params:
      querystring:
        tree: [ "jobs[name,url,lastBuild[number,result,duration,timestamp],builds[number,result,timestamp]]" ]
      header:
      body:
  - name: "jobs_with_builds"
    vars:
      service: "jobs"
    endpoint: "{{domain}}/api/json"
    current_base_key: ["jobs"]
    desired_base_key: ["Jobs"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.cloudbees.{{service}}"]
    documentation: ""
    params:
      querystring:
        tree: ["jobs[name,url,lastBuild[number,result,duration,timestamp],builds[number,result,timestamp]]"]
      header:
      body:
  - name: "alerts"
    vars:
      service: "monitoring-alerts"
    endpoint: "{{domain}}/{{service}}/api/json"
    current_base_key: ["conditions"]
    desired_base_key: ["Alerts"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.cloudbees.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
