---
# TODO: Expand this with more of the API.
name: "srenity"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
  indicator_to_structure: "null_value"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "TokenAuth"
  - "{{}}" # Token 
endpoints: 
  - name: "user_plugins"
    vars:
      service: "user_plugins"
    endpoint: "https://srenitydashboard.io/api/v1/{{service}}.json"
    current_base_key: [""]
    desired_base_key: ["Plugins"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
      body:
