---
# TODO: Expand this with more of the API.
name: "srenity"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Token {{}}:{{}}" # "Token key:secret"
endpoints:
  - name: "user_plugins"
    vars:
      service: "user_plugins"
    endpoint: "INSIGHTS_URL/api/v1/{{service}}.json"
    use_for_connection_check: true
    current_base_key: [""]
    desired_base_key: ["Plugins"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
      body:
