---
# TODO: Expand this with more of the API.
name: "heroku"
paging:
  location_from: ""
  location_to: ""
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Bearer {{}}" # "Bearer " + Token <= Notice the space after 'Bearer' and caps
endpoints:
  - name: "connectionCheck"
    vars:
      service: "account_invoices"
    endpoint: "https://api.heroku.com/account/invoices"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "" ]
    desired_base_key: [ "Invoices" ]
    current_error_key: [ "message" ]
    desired_error_key: [ "Errors" ]
    documentation: "https://devcenter.heroku.com/articles/platform-api-reference#invoice-list"
    params:
      querystring:
      header:
        Accept: [ "application/vnd.heroku+json; version=3" ]
      body:
  - name: "apps"
    vars:
      service: "apps"
    endpoint: "https://api.heroku.com/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Applications"]
    current_error_key: ["message"]
    desired_error_key: ["Errors.heroku.{{service}}"]
    documentation: "https://devcenter.heroku.com/articles/platform-api-reference#app"
    params:
      querystring:
      header:
        Accept: ["application/vnd.heroku+json; version=3"]
      body:
    endpoints:
      id:
        - name: "builds"
          vars:
            service: "builds"
          endpoint: "https://api.heroku.com/apps/{{endpoint_key}}/{{service}}"
          current_base_key: [""]
          desired_base_key: ["ApplicationBuilds"]
          current_error_key: ["message"]
          desired_error_key: ["Errors.heroku.{{service}}"]
          endpoint_key_names:
            name: app_name
          documentation: "https://devcenter.heroku.com/articles/platform-api-reference#build"
          params:
            querystring:
            header:
              Accept: ["application/vnd.heroku+json; version=3"]
            body:
        - name: "domains"
          vars:
            service: "domains"
          endpoint: "https://api.heroku.com/apps/{{endpoint_key}}/{{service}}"
          current_base_key: [""]
          desired_base_key: ["ApplicationDomains"]
          current_error_key: ["message"]
          desired_error_key: ["Errors.heroku.{{service}}"]
          endpoint_key_names:
            name: app_name
          documentation: "https://devcenter.heroku.com/articles/platform-api-reference#domain-list"
          params:
            querystring:
            header:
              Accept: ["application/vnd.heroku+json; version=3"]
            body:
        - name: "dynos"
          vars:
            service: "dynos"
          endpoint: "https://api.heroku.com/apps/{{endpoint_key}}/{{service}}"
          current_base_key: [""]
          desired_base_key: ["Dynos"]
          current_error_key: ["message"]
          desired_error_key: ["Errors.heroku.{{service}}"]
          documentation: "https://devcenter.heroku.com/articles/platform-api-reference#dyno"
          params:
            querystring:
            header:
              Accept: ["application/vnd.heroku+json; version=3"]
            body:
        - name: "releases"
          vars:
            service: "releases"
          endpoint: "https://api.heroku.com/apps/{{endpoint_key}}/{{service}}"
          current_base_key: [""]
          desired_base_key: ["Releases"]
          current_error_key: ["message"]
          desired_error_key: ["Errors.heroku.{{service}}"]
          documentation: "https://devcenter.heroku.com/articles/platform-api-reference#release-list"
          params:
            querystring:
            header:
              Accept: ["application/vnd.heroku+json; version=3"]
            body:
  - name: "account_invoices"
    vars:
      service: "account_invoices"
    endpoint: "https://api.heroku.com/account/invoices"
    current_base_key: [""]
    desired_base_key: ["Invoices"]
    current_error_key: ["message"]
    desired_error_key: ["Errors.heroku.{{service}}"]
    documentation: "https://devcenter.heroku.com/articles/platform-api-reference#invoice-list"
    params:
      querystring:
      header:
        Accept: ["application/vnd.heroku+json; version=3"]
      body:
  - name: "spaces"
    vars:
      service: "spaces"
    endpoint: "https://api.heroku.com/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Spaces"]
    current_error_key: ["message"]
    desired_error_key: ["Errors.heroku.{{service}}"]
    documentation: "https://devcenter.heroku.com/articles/platform-api-reference#space-space-list-1"
    params:
      querystring:
      header:
        Accept: ["application/vnd.heroku+json; version=3"]
      body:
