---
# TODO: Expand this with more of the API.
name: "heroku"
paging:
  location_from: ""
  location_to: ""
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "{{}}" # "Bearer " + Token <= Notice the space after 'Bearer' and caps
endpoints: 
  - name: "apps"
    vars:
      service: "apps"
    endpoint: "https://api.heroku.com/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Applications"]
    current_error_key: ["message"]
    desired_error_key: ["Errors.heroku.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
        Accept: ["application/vnd.heroku+json; version=3"]
      body:
