---
# TODO: Expand this with more of the API.
name: "datadog"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomQuerystringAuth"
  - "api_key"
  - "{{}}" # API Key
  - "application_key"
  - "{{}}" # Application Key
endpoints:
  - name: "connectionCheck"
    vars:
      service: "cpu"
    endpoint: "https://app.datadoghq.com/api/v1/query"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "series" ]
    desired_base_key: [ "Cpu.Idle" ]
    current_error_key: [ "errors" ]
    desired_error_key: [ "Errors" ]
    documentation: ""
    params:
      querystring:
        query: [ "system.cpu.idle{*}by{host}" ]
        from: [ "{{time:-24h}}" ]
        to: [ "{{time:now}}" ]
      header:
      body:
  - name: "cpu"
    vars:
      service: "cpu"
    endpoint: "https://app.datadoghq.com/api/v1/query"
    current_base_key: ["series"]
    desired_base_key: ["Cpu.Idle"]
    current_error_key: ["errors"]
    desired_error_key: ["Errors.{{service}}.cpu"]
    documentation: ""
    params:
      querystring:
        query: [ "system.cpu.idle{*}by{host}" ]
        from: [ "{{time:-24h}}" ]
        to: [ "{{time:now}}" ]
      header:
      body:
  - name: "metrics"
    vars:
      service: "metrics"
    endpoint: "https://app.datadoghq.com/api/v1/{{service}}"
    current_base_key: ["metrics"]
    desired_base_key: ["Metrics"]
    current_error_key: ["errors"]
    desired_error_key: ["Errors.{{service}}.metrics"]
    documentation: ""
    params:
      querystring:
        from: [ "{{time:-720h}}" ]
      header:
      body:
