---
# TODO: Expand this with more of the API.
name: "assembla"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "X-Api-Key"
  - "{{}}" # Api Key
  - "X-Api-Secret"
  - "{{}}" # Api Secret
endpoints:
  - name: "spaces"
    vars:
      service: "spaces"
    endpoint: "https://api.assembla.com/v1/{{service}}.json"
    current_base_key: [""]
    desired_base_key: ["Spaces"]
    current_error_key: ["error_description"]
    desired_error_key: ["Errors.assembla.{{service}}"]
    documentation: "https://api-docs.assembla.cc/content/ref/spaces_index.html"
    params:
      querystring:
      header:
      body:
    endpoints:
      id:
        - name: "milestones"
          vars:
            service: "milestones"
          endpoint: "https://api.assembla.com/v1/spaces/{{endpoint_key}}/{{service}}/all.json"
          current_base_key: [""]
          desired_base_key: ["Milestones"]
          current_error_key: ["error_description"]
          desired_error_key: ["Errors.assembla.{{service}}"]
          documentation: "https://api-docs.assembla.cc/content/ref/milestones_all.html"
          endpoint_key_names:
            name: space_name
          params:
            querystring:
            header:
            body:
        - name: "tickets"
          vars:
            service: "tickets"
          endpoint: "https://api.assembla.com/v1/spaces/{{endpoint_key}}/{{service}}.json"
          current_base_key: [""]
          desired_base_key: ["Tickets"]
          current_error_key: ["error_description"]
          desired_error_key: ["Errors.assembla.{{service}}"]
          documentation: "https://api-docs.assembla.cc/content/ref/tickets_all.html"
          endpoint_key_names:
            name: space_name
          params:
            querystring:
            header:
            body:
