---
# TODO: Expand this with more of the API.
name: "bitbucket"
paging:
  location_to: "querystring"
  indicator_from_field: "next"
  indicator_to_field: "after"
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}" # Username
  - "{{}}" # Password
global_vars:
  username: "USERNAME"
endpoints:
  - name: "repos"
    vars:
      service: "repositories"
    endpoint: "https://api.bitbucket.org/2.0/{{service}}/{{username}}"
    current_base_key: ["values"]
    desired_base_key: ["Repositories"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: "https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories"
    params:
      querystring:
      header:
      body:
    endpoints:
      "values.full_name":
        - name: "pull_requests"
          vars:
            service: "pullrequests"
          endpoint: "https://api.bitbucket.org/2.0/repositories/{{endpoint_key}}/{{service}}"
          current_base_key: ["values"]
          desired_base_key: ["PullRequests"]
          current_error_key: [""]
          desired_error_key: [""]
          documentation: "https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests"
          params:
            querystring:
            header:
            body:
