---
# TODO: Expand this with more of the API.
name: "bitbucket"
paging:
  location_to: "querystring"
  indicator_from_field: "next"
  indicator_to_field: "after"
  indicator_from_structure: "full_url"
  indicator_to_structure: "null_value"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}" # Username
  - "{{}}" # Password
endpoints: 
  - name: "repos"
    vars:
      service: "repositories"
      username: "USERNAME"
    endpoint: "https://api.bitbucket.org/2.0/{{service}}/{{username}}"
    current_base_key: ["values"]
    desired_base_key: ["Respositories"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
      body:
