---
name: "circleci"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomQuerystringAuth"
  - "circle-token"
  - "{{}}" # Token
endpoints:
  - name: "connectionCheck"
    vars:
      service: "projects"
    endpoint: "https://circleci.com/api/v1.1/{{service}}"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "" ]
    desired_base_key: [ "Projects" ]
    current_error_key: [ "message" ]
    desired_error_key: [ "Errors" ]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "projects"
    vars:
      service: "projects"
    endpoint: "https://circleci.com/api/v1.1/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Projects"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "recent_builds"
    vars:
      service: "recent_builds"
    endpoint: "https://circleci.com/api/v1.1/recent-builds"
    current_base_key: [""]
    desired_base_key: ["RecentBuilds"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: "https://circleci.com/docs/api/#recent-builds-across-all-projects"
    params:
      querystring:
        shallow: ["true"]
        limit: ["100"]
      header:
      body:
