---
name: "bamboo"
paging:
  location_from: ""
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}"
  - "{{}}"
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  domain: "DOMAIN"
endpoints:
  - name: "builds"
    vars:
      service: "builds"
    endpoint: "{{domain}}/rest/api/latest/result"
    current_base_key: ["results.result"]
    desired_base_key: ["Builds"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.bamboo.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
        Accept: ["application/json"]
      body:
