---
name: "bamboo"
paging:
  location_from: ""
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}"
  - "{{}}"
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  domain: "DOMAIN"
endpoints:
  - name: "queue"
    vars:
      service: "queue"
    endpoint: "{{domain}}/rest/api/latest/{{service}}.json"
    current_base_key: ["queuedBuilds"]
    desired_base_key: ["QueuedBuildsStats"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.bamboo.{{service}}"]
    documentation: "https://developer.atlassian.com/server/bamboo/bamboo-rest-resources/#build-queue-service"
    params:
      querystring:
        os_type: ["authBasic"]
      header:
      body:
  - name: "plans"
    vars:
      service: "plan"
    endpoint: "{{domain}}/rest/api/latest/{{service}}.json"
    current_base_key: ["plans.plan"]
    desired_base_key: ["Plans"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.bamboo.{{service}}"]
    documentation: "https://developer.atlassian.com/server/bamboo/bamboo-rest-resources/#plan-service"
    params:
      querystring:
        os_type: ["authBasic"]
      header:
      body:
    endpoints:
      "plans.plan.key":
        - name: "build"
          vars:
            service: "result"
          endpoint: "{{domain}}/rest/api/latest/result/{{endpoint_key}}.json"
          current_base_key: ["results.result"]
          desired_base_key: ["Builds"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.bamboo.{{service}}"]
          documentation: "https://developer.atlassian.com/server/bamboo/bamboo-rest-resources/#build-service----specific-plan"
          params:
            querystring:
              os_type: ["authBasic"]
              expand: ["results.result"]
            header:
            body:
