---
name: "sentry"
paging:
  location_from: "header"
  location_to: "querystring"
  indicator_from_field: "Link"
  indicator_to_field: ""
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Bearer {{}}" # "Bearer " + Token <= Notice the space after 'Bearer'
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\"; results=\"true\""
endpoints:
  - name: "connectionCheck"
    vars:
      service: "organizations"
    endpoint: "https://sentry.io/api/0/{{service}}/"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "" ]
    desired_base_key: [ "Organizations" ]
    current_error_key: [ "detail" ]
    desired_error_key: [ "Errors" ]
    documentation: "https://docs.sentry.io/api/organizations/get-organization-index/"
    params:
      querystring:
      header:
      body:
  - name: "organizations"
    vars:
      service: "organizations"
    endpoint: "https://sentry.io/api/0/{{service}}/"
    current_base_key: [""]
    desired_base_key: ["Organizations"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.sentry.{{service}}"]
    documentation: "https://docs.sentry.io/api/organizations/get-organization-index/"
    params:
      querystring:
      header:
      body:
    endpoints:
      slug:
        - name: "releases"
          vars:
            service: "releases"
          endpoint: "https://sentry.io/api/0/organizations/{{endpoint_key}}/{{service}}/"
          current_base_key: [""]
          desired_base_key: ["Releases"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.sentry.{{service}}"]
          endpoint_key_names:
            slug: organization_slug
          documentation: ""
          params:
            querystring:
            header:
            body:
        - name: "projects"
          vars:
            service: "projects"
          endpoint: "https://sentry.io/api/0/organizations/{{endpoint_key}}/{{service}}/"
          current_base_key: [""]
          desired_base_key: ["Projects"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.sentry.{{service}}"]
          endpoint_key_names:
            slug: organization_slug
          documentation: ""
          params:
            querystring:
            header:
            body:
          endpoints:
            slug:
              - name: "issues"
                vars:
                  service: "issues"
                endpoint: "https://sentry.io/api/0/projects/{{organization_slug}}/{{endpoint_key}}/{{service}}/"
                current_base_key: [""]
                desired_base_key: ["Issues"]
                current_error_key: ["error"]
                desired_error_key: ["Errors.sentry.{{service}}"]
                endpoint_key_names:
                  organization_slug: organization_slug
                  slug: project_slug
                documentation: "https://docs.sentry.io/api/events/get-project-group-index/"
                params:
                  querystring:
                  header:
                  body:
