---
# TODO: Expand this with more of the API.
name: "sentry"
paging:
  location_from: "header"
  location_to: "querystring"
  indicator_from_field: "Link"
  indicator_to_field: ""
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "{{}}" # "Bearer " + Token <= Notice the space after 'Bearer'
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\"; results=\"true\""
endpoints: 
  - name: "projects"
    vars:
      service: "projects"
    endpoint: "https://sentry.io/api/0/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Projects"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.sentry.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
