---
# TODO: Expand this with more of the API.
name: "teamcity"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
  indicator_to_structure: "null_value"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Bearer {{}}" # Token
global_vars:
  url: "URL"
endpoints:
  - name: "projects"
    vars:
      service: "projects"
    endpoint: "{{url}}/app/rest/latest/{{service}}"
    current_base_key: ["project"]
    desired_base_key: ["Projects"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
        Accept: ["application/json"]
      body:
    endpoints:
      "project.id":
        - name: "builds"
          vars:
            service: "builds"
          endpoint: "{{url}}/app/rest/latest/{{service}}"
          current_base_key: ["build"]
          desired_base_key: ["ProjectBuilds"]
          current_error_key: [""]
          desired_error_key: [""]
          endpoint_key_names:
            "project.name": project_name
          documentation: ""
          params:
            querystring:
              locator: ["affectedProject:(id:{{endpoint_key}}),count:1"]
            header:
              Accept: ["application/json"]
            body:
