---
# TODO: Expand this with more of the API.
name: "teamcity"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
  indicator_to_structure: "null_value"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}" # Username
  - "{{}}" # Password
endpoints: 
  - name: "projects"
    vars:
      service: "projects"
    endpoint: "https://YOUR_TC_URL/app/rest/latest/{{service}}"
    current_base_key: ["project"]
    desired_base_key: ["Projects"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: ""
    params:
      querystring:
      header:
      body:
