name: "gcpinfra"
paging:
  location_to: "body"
  indicator_from_field: "pageToken"
  indicator_to_field: "pageToken"
  indicator_from_structure: "param"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "JwtAuth"
  - "{{}}" # Key Email
  - "{{}}" # Private Key
  - "{{}}" # Private Key ID
  - "{{}}" # Scopes (comma delimited string)
  - "{{}}" # Token URL
global_vars:
  project: "PROJECT"
endpoints:
  - name: "healthChecks"
    vars:
      service: "healthChecks"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["HealthChecks"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: "https://cloud.google.com/compute/docs/reference/rest/v1/healthChecks/list"
    params:
      querystring:
      header:
      body:
  - name: "zonesList"
    vars:
      service: "zones"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["Zones"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "imagesList"
    vars:
      service: "images"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["Images"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "instancesList"
    vars:
      service: "instances"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/aggregated/{{service}}"
    current_base_key: ["items.zones/us-central1-a.instances", "items.zones/us-central1-b.instances", "items.zones/us-central1-c.instances"]
    desired_base_key: ["Instances", "Instances", "Instances"]
    current_error_key: ["error.errors","error.errors","error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}","Errors.gcp.{{service}}","Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "projectsList"
    vars:
      service: "projects"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}"
    current_base_key: ["items"]
    desired_base_key: ["Projects"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "backendBuckets"
    vars:
      service: "backendBuckets"
    endpoint: "https://compute.googleapis.com/compute/beta/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["BackendBuckets"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "firewalls"
    vars:
      service: "firewalls"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["Firewalls"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "urlMaps"
    vars:
      service: "urlMaps"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["URLMaps"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: "https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps/list"
    params:
      querystring:
      header:
      body:
  - name: "autoscalers"
    vars:
      service: "autoscalers.list"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/aggregated/autoscalers"
    current_base_key: ["items.regions/us-central1.autoscalers"]
    desired_base_key: ["autoscalers"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: "https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps/list"
    params:
      querystring:
      header:
      body:
  - name: "instanceGroup"
    vars:
      service: "instanceGroupManagers.list"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/aggregated/instanceGroupManagers"
    current_base_key: ["items.regions/us-central1.instanceGroupManagers"]
    desired_base_key: ["InstanceGroupManagers"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: "https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps/list"
    params:
      querystring:
      header:
      body:
  - name: "instanceGroup"
    vars:
      service: "instanceGroup.list"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/aggregated/instanceGroups"
    current_base_key: ["items.regions/us-central1.instanceGroups"]
    desired_base_key: ["InstanceGroups"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "instanceTemplates"
    vars:
      service: "instanceTemplates.list"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/instanceTemplates"
    current_base_key: ["items"]
    desired_base_key: ["InstanceTemplates"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation: "https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/list"
    params:
      querystring:
      header:
      body:
  - name: "networks"
    vars:
      service: "networks"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/global/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["Networks"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "database_instances"
    vars:
      service: "instances"
    endpoint: "https://www.googleapis.com/sql/v1beta4/projects/{{project}}/{{service}}"
    current_base_key: ["items"]
    desired_base_key: ["DBInstances"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
    endpoints:
      id:
        - name: "databases"
          vars:
            service: "databases"
          endpoint: "https://www.googleapis.com/sql/v1beta4/projects/{{project}}/instances/{{endpoint_key}}/{{service}}"
          current_base_key: ["items"]
          desired_base_key: ["InstanceDatabases"]
          current_error_key: ["error.errors"]
          desired_error_key: ["Errors.gcp.{{service}}"]
          documentation:
          params:
            querystring:
            header:
            body:
  - name: "kms_locations"
    vars:
      service: "kms_locations"
    endpoint: "https://cloudkms.googleapis.com/v1/projects/{{project}}/locations"
    current_base_key: ["locations"]
    desired_base_key: ["KMSLocations"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
    endpoints:
      "locations.id":
        - name: "kms_keyrings"
          vars:
            service: "kms_keyrings"
          endpoint: "https://cloudkms.googleapis.com/v1/projects/{{project}}/locations/{{endpoint_key}}/keyRings"
          current_base_key: ["keyRings"]
          desired_base_key: ["KMSLocationsKeyrings"]
          current_error_key: ["error.errors"]
          desired_error_key: ["Errors.gcp.{{service}}"]
          endpoint_key_names:
            "locations.id": location_id
          documentation:
          params:
            querystring:
            header:
            body:
          endpoints:
            "keyRings.id":
              - name: "kms_keyrings_crypto_keys"
                vars:
                  service: "kms_keyrings_crypto_keys"
                endpoint: "https://cloudkms.googleapis.com/v1/projects/{{project}}/locations/{{location_id}}/keyRings/{{endpoint_key}}/cryptoKeys"
                current_base_key: ["cryptoKeys"]
                desired_base_key: ["KMSLocationsKeyringsCryptoKeys"]
                current_error_key: ["error.errors"]
                desired_error_key: ["Errors.gcp.{{service}}"]
                endpoint_key_names:
                  "keyrings.id": keyring_id
                  location_id: location_id
                documentation:
                params:
                  querystring:
                  header:
                  body:
                endpoints:
                  "cryptoKeys.id":
                    - name: "kms_keyrings_crypto_keys_versions"
                      vars:
                        service: "kms_keyrings_crypto_keys_versions"
                      endpoint: "https://cloudkms.googleapis.com/v1/projects/{{project}}/locations/{{location_id}}/keyRings/{{keyring_id}}/cryptoKeys/{{endpoint_key}}/cryptoKeyVersions"
                      current_base_key: ["cryptoKeyVersions"]
                      desired_base_key: ["KMSLocationsKeyringsCryptoKeysVersions"]
                      current_error_key: ["error.errors"]
                      desired_error_key: ["Errors.gcp.{{service}}"]
                      endpoint_key_names:
                        keyring_id: keyring_id
                        location_id: location_id
                      documentation:
                      params:
                        querystring:
                        header:
                        body:
  - name: "projects.sinks"
    vars:
      service: "projects.sinks.list"
    endpoint: "https://logging.googleapis.com/v2/projects/{{project}}/sinks"
    current_base_key: ["sinks"]
    desired_base_key: ["Sinks"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "projects.alertPolicies"
    vars:
      service: "projects.alertPolicies.list"
    endpoint: "https://monitoring.googleapis.com/v3/projects/{{project}}/alertPolicies"
    current_base_key: ["alertPolicies"]
    desired_base_key: ["AlertPolicies"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "projects.notificationChannels"
    vars:
      service: "projects.notificationChannels.list"
    endpoint: "https://monitoring.googleapis.com/v3/projects/{{project}}/notificationChannels"
    current_base_key: ["notificationChannels"]
    desired_base_key: ["NotificationChannels"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "Metrics"
    vars:
      service: "metrics"
    endpoint: "https://logging.googleapis.com/v2/projects/{{project}}/{{service}}"
    current_base_key: ["metrics"]
    desired_base_key: ["Metrics"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "managed_zones"
    vars:
      service: "managedZones"
    endpoint: "https://dns.googleapis.com/dns/v1/projects/{{project}}/{{service}}"
    current_base_key: ["managedZones"]
    desired_base_key: ["ManagedZones"]
    current_error_key: ["error.errors"]
    desired_error_key: ["Errors.gcp.{{service}}"]
    documentation:
    params:
      querystring:
      header:
      body:
  - name: "aggregated_subnetworks"
    vars:
      service: "subnetworks"
    endpoint: "https://compute.googleapis.com/compute/v1/projects/{{project}}/aggregated/{{service}}"
    current_base_key: ["items.global.subnetworks", "items.regions/us-central1.subnetworks", "items.regions/europe-west1.subnetworks", "items.regions/us-west1.subnetworks", "items.regions/asia-east1.subnetworks", "items.regions/us-east1.subnetworks", "items.regions/asia-northeast1.subnetworks", "items.regions/asia-southeast1.subnetworks", "items.regions/us-east4.subnetworks", "items.regions/australia-southeast1.subnetworks", "items.regions/europe-west2.subnetworks", "items.regions/europe-west3.subnetworks", "items.regions/southamerica-east1.subnetworks", "items.regions/asia-south1.subnetworks", "items.regions/northamerica-northeast1.subnetworks", "items.regions/europe-west4.subnetworks", "items.regions/europe-north1.subnetworks", "items.regions/us-west2.subnetworks", "items.regions/asia-east2.subnetworks"]
    desired_base_key: ["Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks", "Subnetworks"]
    current_error_key: ["items.global.warning", "items.regions/us-central1.warning", "items.regions/europe-west1.warning", "items.regions/us-west1.warning", "items.regions/asia-east1.warning", "items.regions/us-east1.warning", "items.regions/asia-northeast1.warning", "items.regions/asia-southeast1.warning", "items.regions/us-east4.warning", "items.regions/australia-southeast1.warning", "items.regions/europe-west2.warning", "items.regions/europe-west3.warning", "items.regions/southamerica-east1.warning", "items.regions/asia-south1.warning", "items.regions/northamerica-northeast1.warning", "items.regions/europe-west4.warning", "items.regions/europe-north1.warning", "items.regions/us-west2.warning", "items.regions/asia-east2.warning"]
    desired_error_key: ["Errors.gcp.{{service}}.global", "Errors.gcp.{{service}}.regions/us-central1", "Errors.gcp.{{service}}.regions/europe-west1", "Errors.gcp.{{service}}.regions/us-west1", "Errors.gcp.{{service}}.regions/asia-east1", "Errors.gcp.{{service}}.regions/us-east1", "Errors.gcp.{{service}}.regions/asia-northeast1", "Errors.gcp.{{service}}.regions/asia-southeast1", "Errors.gcp.{{service}}.regions/us-east4", "Errors.gcp.{{service}}.regions/australia-southeast1", "Errors.gcp.{{service}}.regions/europe-west2", "Errors.gcp.{{service}}.regions/europe-west3", "Errors.gcp.{{service}}.regions/southamerica-east1", "Errors.gcp.{{service}}.regions/asia-south1", "Errors.gcp.{{service}}.regions/northamerica-northeast1", "Errors.gcp.{{service}}.regions/europe-west4", "Errors.gcp.{{service}}.regions/europe-north1", "Errors.gcp.{{service}}.regions/us-west2", "Errors.gcp.{{service}}.regions/asia-east2"]
    documentation: ""
    params:
      querystring:
      header:
      body:
