---
# TODO: Expand this with more of the API.
name: "cloudflare"
paging:
  location_to: "querystring"
  indicator_from_field: "result_info.page,result_info.per_page,result_info.total_count"
  indicator_to_field: "page"
  indicator_from_structure: "calculated"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Bearer {{}}" # API token
paging_params:
  - "CalculatePagingPeek"
endpoints:
  - name: "zones"
    vars:
      service: "zones"
    endpoint: "https://api.cloudflare.com/client/v4/{{service}}"
    current_base_key: ["result"]
    desired_base_key: ["Zones"]
    current_error_key: ["errors"]
    desired_error_key: ["Errors.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
