---
name: "cloudflare"
paging:
  location_to: "querystring"
  indicator_from_field: "result_info.page,result_info.per_page,result_info.total_count"
  indicator_to_field: "page"
  indicator_from_structure: "calculated"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "Bearer {{}}" # API token
paging_params:
  - "CalculatePagingPeek"
endpoints:
  - name: "zones"
    vars:
      service: "zones"
    endpoint: "https://api.cloudflare.com/client/v4/{{service}}"
    current_base_key: ["result"]
    desired_base_key: ["Zones"]
    current_error_key: ["errors"]
    desired_error_key: ["Errors.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
    endpoints:
      "result.id":
        - name: "dns_metrics"
          vars:
            service: "dns_analytics"
          endpoint: "https://api.cloudflare.com/client/v4/zones/{{endpoint_key}}/{{service}}/report"
          current_base_key: ["result"]
          desired_base_key: ["DNSAnalytics"]
          current_error_key: ["errors"]
          desired_error_key: ["Errors.cloudflare.{{service}}"]
          endpoint_key_names:
            "result.name": zone_name
          documentation: "https://api.cloudflare.com/#dns-analytics-table"
          params:
            querystring:
              metrics: ["queryCount,uncachedCount,staleCount,responseTimeAvg"]
            header:
            body:
  - name: "accounts"
    vars:
      service: "accounts"
    endpoint: "https://api.cloudflare.com/client/v4/{{service}}"
    current_base_key: ["result"]
    desired_base_key: ["Accounts"]
    current_error_key: ["errors"]
    desired_error_key: ["Errors.cloudflare.{{service}}"]
    documentation: "https://api.cloudflare.com/#accounts-list-accounts"
    params:
      querystring:
      header:
      body:
    endpoints:
      "result.id":
        - name: "dns_firewall_clusters"
          vars:
            service: "virtual_dns"
          endpoint: "https://api.cloudflare.com/client/v4/accounts/{{endpoint_key}}/{{service}}"
          current_base_key: ["result"]
          desired_base_key: ["DNSFirewallClusters"]
          current_error_key: ["errors"]
          desired_error_key: ["Errors.cloudflare.{{service}}"]
          endpoint_key_names:
            "result.name": account_name
            "result.id": account_id
          documentation: "https://api.cloudflare.com/#dns-analytics-table"
          params:
            querystring:
            header:
            body:
          endpoints:
            "result.id":
              - name: "dns_firewall_analytics"
                vars:
                  service: "dns_firewall_analytics"
                endpoint: "https://api.cloudflare.com/client/v4/accounts/{{account_id}}/{{endpoint_key}}/dns_analytics/report"
                current_base_key: ["result"]
                desired_base_key: ["DNSFirewallAnalytics"]
                current_error_key: ["errors"]
                desired_error_key: ["Errors.cloudflare.{{service}}"]
                endpoint_key_names:
                  account_name: account_name
                  account_id: account_id
                documentation: "https://api.cloudflare.com/#dns-firewall-analytics-accounts--table"
                params:
                  querystring:
                  header:
                  body:
