---
name: "rollbar"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomQuerystringAuth"
  - "access_token"
  - "{{}}" # Token
endpoints:
  - name: "deploys"
    vars:
      service: "deploys"
    endpoint: "https://api.rollbar.com/api/1/{{service}}"
    current_base_key: ["result.deploys"]
    desired_base_key: ["Deploys"]
    current_error_key: ["message"]
    desired_error_key: [""]
    documentation: "https://explorer.docs.rollbar.com/#operation/list-all-deploys"
    params:
      querystring:
      header:
      body:
  - name: "items"
    vars:
      service: "items"
    endpoint: "https://api.rollbar.com/api/1/{{service}}"
    current_base_key: ["result.items"]
    desired_base_key: ["Items"]
    current_error_key: ["message"]
    desired_error_key: [""]
    documentation: "https://explorer.docs.rollbar.com/#operation/list-all-items"
    params:
      querystring:
      header:
      body:
