name: "newrelic"
paging:
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "X-Api-Key"
  - "{{}}" # Api Key
endpoints:
  - name: "connectionCheck"
    vars:
      service: "alerts_policies"
    endpoint: "https://api.newrelic.com/v2/{{service}}.json"
    use_for_connection_check: true
    skip_for_scans: true
    current_base_key: [ "policies" ]
    desired_base_key: [ "Policies" ]
    current_error_key: [ "error.title" ]
    desired_error_key: [ "Errors" ]
    documentation: "https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/rest-api-calls-new-relic-alerts"
    params:
      querystring:
      header:
      body:
  - name: "applications"
    vars:
      service: "applications"
    endpoint: "https://api.newrelic.com/v2/{{service}}.json"
    current_base_key: ["applications"]
    desired_base_key: ["Applications"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
    endpoints:
      id:
        - name: "metrics"
          vars:
            service: "metrics"
          endpoint: "https://api.newrelic.com/v2/applications/{{endpoint_key}}/{{service}}/data.json"
          current_base_key: ["metric_data"]
          desired_base_key: ["MetricData"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.{{service}}"]
          documentation: "https://docs.newrelic.com/docs/apis/rest-api-v2/browser-examples-v2/obtaining-browser-end-user-page-load-time-data-v2#DOM_processing_time"
          endpoint_key_names:
            id: app_id
          params:
            querystring:
              names: ["EndUser/RB"]
              values: ["average_dom_content_load_time"]
            header:
            body:
  - name: "alerts_policies"
    vars:
      service: "alerts_policies"
    endpoint: "https://api.newrelic.com/v2/{{service}}.json"
    current_base_key: ["policies"]
    desired_base_key: ["Policies"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.{{service}}"]
    documentation: "https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/rest-api-calls-new-relic-alerts"
    params:
        querystring:
        header:
        body:
