---
# TODO: Expand this with more of the API.
name: "github"
paging:
  location_from: "header"
  location_to: "querystring"
  indicator_from_field: "Link"
  indicator_to_field: ""
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}" # Username
  - "{{}}" # Personal access token
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
endpoints:
  - name: "repos"
    vars:
      service: "repos"
    endpoint: "https://api.github.com/user/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Repos"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.github.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
