name: "onelogin"
paging:
  location_to: "querystring"
  indicator_from_field: "pagination.next_link"
  indicator_to_field: ""
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "Oauth2TwoLegAuth"
  - "{{}}" # Client ID
  - "{{}}" # Client Secret
  - "{{}}" # Scopes (comma delimited string)
  - "https://api.us.onelogin.com/auth/oauth2/token" # Token URL
  - "{{}}" # Endpoint params (string with ":" key/value separator and "," between
# TODO: support both US and EU
endpoints:
  - name: "users"
    vars:
      service: "users"
    endpoint: "https://api.us.onelogin.com/api/1/{{service}}"
    current_base_key: ["data"]
    desired_base_key: ["Users"]
    current_error_key: [""]
    desired_error_key: [""]
    documentation: "https://developers.onelogin.com/api-docs/1/users/get-users"
    params:
      querystring:
      header:
      body:
  - name: "events"
    vars:
      service: "events"
    endpoint: "https://api.us.onelogin.com/api/1/{{service}}"
    current_base_key: ["data"]
    desired_base_key: ["Events"]
    current_error_key: ["status.error"]
    desired_error_key: ["Errors.onelogin.{{service}}"]
    documentation: "https://developers.onelogin.com/api-docs/1/events/get-events"
    params:
      querystring:
      header:
      body:
  - name: "scores"
    vars:
      service: "scores"
    endpoint: "https://api.us.onelogin.com/api/2/risk/{{service}}"
    current_base_key: ["scores", "total"]
    desired_base_key: ["Scores", "Total"]
    current_error_key: ["status.error"]
    desired_error_key: ["Errors.onelogin.{{service}}"]
    documentation: "https://developers.onelogin.com/api-docs/2/vigilance/get-scores"
    params:
      querystring:
      header:
      body:
  - name: "rules"
    vars:
      service: "rules"
    endpoint: "https://api.us.onelogin.com/api/2/risk/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Rules"]
    current_error_key: ["status.error"]
    desired_error_key: ["Errors.onelogin.{{service}}"]
    documentation: "https://developers.onelogin.com/api-docs/2/vigilance/get-rules"
    params:
      querystring:
      header:
      body:
  - name: "apps"
    vars:
      service: "apps"
    endpoint: "https://api.us.onelogin.com/api/2/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Apps"]
    current_error_key: ["status.error"]
    desired_error_key: ["Errors.onelogin.{{service}}"]
    documentation: "https://developers.onelogin.com/api-docs/2/apps/list-apps"
    params:
      querystring:
      header:
      body:
    endpoints:
      id:
        - name: "apps_details"
          vars:
            service: "apps"
          endpoint: "https://api.us.onelogin.com/api/2/{{service}}/{{endpoint_key}}"
          current_base_key: ["configuration"]
          desired_base_key: ["Configuration"]
          current_error_key: ["status.error"]
          desired_error_key: ["Errors.onelogin.{{service}}"]
          documentation: "https://developers.onelogin.com/api-docs/2/apps/get-app"
          endpoint_key_names:
            id: app_id
          params:
            querystring:
            header:
            body:
