name: "okta"
paging:
  location_from: "header"
  location_to: "querystring"
  indicator_from_field: "Link"
  indicator_to_field: ""
  indicator_from_structure: "full_url"
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "CustomHeaderAuth"
  - "Authorization"
  - "SSWS {{}}" # "SSWS " + Token <= Notice the space after 'SSWS'
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  subdomain: "SUBDOMAIN"
endpoints:
  - name: "users"
    vars:
      service: "users"
    endpoint: "https://{{subdomain}}.okta.com/api/v1/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Users"]
    current_error_key: ["errorCauses"]
    desired_error_key: ["Errors.okta.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "apps"
    vars:
      service: "apps"
    endpoint: "https://{{subdomain}}.okta.com/api/v1/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Apps"]
    current_error_key: ["errorCauses"]
    desired_error_key: ["Errors.okta.{{service}}"]
    documentation: ""
    params:
      querystring:
      header:
      body:
  - name: "policies"
    vars:
      service: "policies"
    endpoint: "https://{{subdomain}}.okta.com/api/v1/{{service}}"
    current_base_key: [""]
    desired_base_key: ["Policies"]
    current_error_key: ["errorCauses"]
    desired_error_key: ["Errors.okta.{{service}}"]
    documentation: "https://developer.okta.com/docs/reference/api/policy/#policy-object"
    params:
      querystring:
        type: ["PASSWORD"]
      header:
      body:
  - name: "trusted_origins"
    vars:
      service: "trustedOrigins"
    endpoint: "https://{{subdomain}}.okta.com/api/v1/{{service}}"
    current_base_key: [""]
    desired_base_key: ["TrustedOrigins"]
    current_error_key: ["errorCauses"]
    desired_error_key: ["Errors.okta.{{service}}"]
    documentation: "https://developer.okta.com/docs/reference/api/trusted-origins/#list-all-trusted-originst"
    params:
      querystring:
      header:
      body:
