---
name: "zendesk"
paging:
  location_from: ""
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}/token"
  - "{{}}"
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  domain: "DOMAIN"
endpoints:
  - name: "groups"
    vars:
      service: "groups"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["groups"]
    desired_base_key: ["Groups"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/groups"
    params:
      querystring:
      header:
      body:
  - name: "users"
    vars:
      service: "users"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["users"]
    desired_base_key: ["Users"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/users"
    params:
      querystring:
      header:
      body:
  - name: "tickets"
    vars:
      service: "tickets"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["tickets"]
    desired_base_key: ["Tickets"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/tickets"
    params:
      querystring:
      header:
      body:
