---
name: "zendesk"
paging:
  location_from: ""
  location_to: "querystring"
  indicator_from_field: ""
  indicator_to_field: ""
  indicator_from_structure: ""
plugin: "FULL_PATH_TO/epico-plugins/plugins/generic-json/generic-json.so"
auth_params:
  - "BasicAuth"
  - "{{}}/token"
  - "{{}}"
paging_params:
  - "RegexJsonPagingPeek"
  - "<([^>]*)>; rel=\"next\""
global_vars:
  domain: "DOMAIN"
endpoints:
  - name: "groups"
    vars:
      service: "groups"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["groups"]
    desired_base_key: ["Groups"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/groups"
    params:
      querystring:
      header:
      body:
    endpoints:
      "groups.id":
        - name: "memberships"
          vars:
            service: "memberships"
          endpoint: "https://{{domain}}.zendesk.com/api/v2/groups/{{endpoint_key}}/{{service}}.json"
          current_base_key: ["group_memberships"]
          desired_base_key: ["GroupMemberships"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.zendesk.{{service}}"]
          endpoint_key_names:
            "groups.name": group_name
          documentation: ""
          params:
            querystring:
            header:
            body:
      "groups.id":
        - name: "groups_details"
          vars:
            service: "groups"
          endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}/{{endpoint_key}}.json"
          current_base_key: ["group"]
          desired_base_key: ["Group"]
          current_error_key: ["error"]
          desired_error_key: ["Errors.zendesk.{{service}}"]
          endpoint_key_names:
            "groups.name": group_name
          documentation: "https://developer.zendesk.com/rest_api/docs/support/groups"
          params:
            querystring:
            header:
            body:
  - name: "users"
    vars:
      service: "users"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["users"]
    desired_base_key: ["Users"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/users"
    params:
      querystring:
      header:
      body:
  - name: "tickets"
    vars:
      service: "tickets"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["tickets"]
    desired_base_key: ["Tickets"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/tickets"
    params:
      querystring:
      header:
      body:
  - name: "job_statuses"
    vars:
      service: "job_statuses"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["job_statuses"]
    desired_base_key: ["JobStatuses"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/job_statuses"
    params:
      querystring:
      header:
      body:
  - name: "ticket_metrics"
    vars:
      service: "ticket_metrics"
    endpoint: "https://{{domain}}.zendesk.com/api/v2/{{service}}.json"
    current_base_key: ["ticket_metrics"]
    desired_base_key: ["TicketMetrics"]
    current_error_key: ["error"]
    desired_error_key: ["Errors.zendesk.{{service}}"]
    documentation: "https://developer.zendesk.com/rest_api/docs/support/ticket_metrics"
    params:
      querystring:
      header:
      body:
